{{- if  .Values.privateNetwork.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: lb-app-one
  annotations: 
    {{- toYaml  .Values.lbAppOne.annotations | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: app-one
  ports:
  {{- .Values.lbAppOne.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-app-two
  annotations: 
    {{- toYaml  .Values.lbAppTwo.annotations | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: app-two
  ports:
  {{- .Values.lbAppTwo.ports | toYaml | nindent 2 }}
{{- end }}