platform: local
privateNetwork:
  enabled: false
pv:
  storageCapacity: 2Gi
  storageClass: ""
  accessModes: ReadOnlyMany
  provisioner: ""
pvc:
  storageRequest: 2Gi
  accessModes: ReadOnlyMany
  storageClass: ""
kedaPrometheusAccess:
  serverAddress: "http://prometheus.monitoring.svc.cluster.local:9090" 
appOne:
  nodeSelector:
      app: app-one
  # For ingress controllerwhen the above privateNetwork.enabled=false
  scaleQuery: "sum(rate(nginx_ingress_controller_requests{service=\"app-one\"}[1m])) / scalar(count(kube_pod_info{namespace=\"default\",pod=~\"app-one.*\"}))" 
appTwo:
  nodeSelector:
    app: app-two
  # For ingress controller when the above privateNetwork.enabled=false
  scaleQuery: "sum(rate(nginx_ingress_controller_requests{service=\"app-two\"}[1m])) / scalar(count(kube_pod_info{namespace=\"default\",pod=~\"app-two.*\"}))"
ingress:
  ingressClassName: nginx
  host: localhost